AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'app/interactors/create_account.rb'

# Customize rules
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
